CREATE TABLE SALES (
SALE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
BK_ID INT, 
COURTFEE_TOTAL DOUBLE,
ITEM_LIST VARCHAR(500),
ITEM_TOTAL DOUBLE,
GRAND_TOTAL DOUBLE NOT NULL,
MONEY_RECEIVED DOUBLE NOT NULL,
BALANCE DOUBLE NOT NULL,
US_ID INT NOT NULL,
DATE_CREATED DATETIME NOT NULL,
DATE_MODIFIED DATETIME,  
FOREIGN KEY FK_BKID (BK_ID)
REFERENCES BOOKINGS (BK_ID),
FOREIGN KEY FK_USERID (US_ID)
REFERENCES USERS (US_ID)
)ENGINE=InnoDB;

