CREATE TABLE BOOKINGS (
BK_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
CUST_NAME VARCHAR(30) NOT NULL,
CUST_CTNO VARCHAR(30) NOT NULL,
BK_DATE VARCHAR(10) NOT NULL,
TIME_DATA VARCHAR(50) NOT NULL,
TIME_DETAIL VARCHAR(500) NOT NULL,
BK_PERIOD INT NOT NULL,
US_ID INT NOT NULL, 
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE,  
FOREIGN KEY FK_USERID (US_ID)
REFERENCES USERS (US_ID)
)ENGINE=InnoDB;

