CREATE TABLE USERS (
US_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
USERNAME VARCHAR(30) NOT NULL UNIQUE,
PASSWORD BLOB NOT NULL,
SALT BLOB NOT NULL,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
POSITION VARCHAR(10) NOT NULL,
DATE_CREATED DATE NOT NULL 
);
